[features]
seeds = false
skip-lint = false
[programs.devnet]
gratie_solana = "6Ki5zkofcL2h3q1F1T9WYUPWwbu9DogCGB5vmLGyi1Ce"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mucks/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
