[features]
seeds = false
skip-lint = false
[programs.localnet]
gratie_solana = "AEf99S19YTaox9E8aX3ugpGJtHTHjaQtSY2ixtLysFGr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/mucks/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
