[features]
seeds = false
skip-lint = false
[programs.testnet]
gratie_solana = "3tk9foNJ24cchnm87KusX9L9BoWhZxzWrhV5hPBUzQcH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "/home/mucks/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
